### ISSUE TITLE
Improve Security

### ISSUE THREAD

**Issue by macskay** [pasteit/pasteit#23]
- [x] Add redis configuration with password #24 
- [ ]  Avoid Cross-site scripting #9 
- [ ] Add rate limiting #36
