### ISSUE TITLE
Legal Issues

### ISSUE THREAD

**Issue by macskay** [pasteit/pasteit#25]
- [ ] Check Legal Issues (What excatly has to be in the Impressum & Disclaimer?) #10 
- [ ] Add Disclaimer page #26 
- [ ] Add Impressum page #27
