### ISSUE TITLE
Create/Edit and Paste View Issues

### ISSUE THREAD

**Issue by macskay** [pasteit/pasteit#29]
All Issues relating to the creation/editing of pastes, as well as vieweing pastes should be grouped in here.

- [x] Add Syntax highlighting - #1 
- [x] Submit pastes to redis #2
- [ ] ~Add hotkeys #3~
- [ ] Add tagging to pastes #8
- [x] Deletion of pastes #11
- [x] Show Language in pastes #15
- [ ] Add version to views #35
