### ISSUE TITLE
Server hardening

### ISSUE THREAD

**Issue by macskay** [pasteit/pasteit#43]
Anyting related to system hardening
- [ ] Setup health system #38
- [x] Enable continuous deployment #41
- [ ] E-mail health issues #39 
- [ ] Load testing #40
