### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by macskay** [pasteit/pasteit#52]
- [ ] Setup unit tests for server code #48
- [ ] Setup unit tests for client code #49
- [ ] Setup integration tests #50
